//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Sales_Manager.RegistrySettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Sales_Manager.WindowSettings WindowSettings {
            get {
                return ((global::Sales_Manager.WindowSettings)(this["WindowSettings"]));
            }
            set {
                this["WindowSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Sales_Manager.RegistrySettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AAEAAAD/////AQAAAAAAAAAMAgAAAFRPYmplY3RMaXN0VmlldywgVmVyc2lvbj0yLjkuMS4xMDcyLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIxYzViZjU4MTQ4MWJjZDQMAwAAAFdTeXN0ZW0uV2luZG93cy5Gb3JtcywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkFAQAAADZCcmlnaHRJZGVhc1NvZnR3YXJlLk9iamVjdExpc3RWaWV3K09iamVjdExpc3RWaWV3U3RhdGUJAAAADVZlcnNpb25OdW1iZXIPTnVtYmVyT2ZDb2x1bW5zC0N1cnJlbnRWaWV3ClNvcnRDb2x1bW4PSXNTaG93aW5nR3JvdXBzDUxhc3RTb3J0T3JkZXIPQ29sdW1uSXNWaXNpYmxlFUNvbHVtbkRpc3BsYXlJbmRpY2llcwxDb2x1bW5XaWR0aHMAAAQAAAQDAwMICBlTeXN0ZW0uV2luZG93cy5Gb3Jtcy5WaWV3AwAAAAgBHlN5c3RlbS5XaW5kb3dzLkZvcm1zLlNvcnRPcmRlcgMAAAAcU3lzdGVtLkNvbGxlY3Rpb25zLkFycmF5TGlzdBxTeXN0ZW0uQ29sbGVjdGlvbnMuQXJyYXlMaXN0HFN5c3RlbS5Db2xsZWN0aW9ucy5BcnJheUxpc3QCAAAAAQAAAAUAAAAF/P///xlTeXN0ZW0uV2luZG93cy5Gb3Jtcy5WaWV3AQAAAAd2YWx1ZV9fAAgDAAAAAQAAAAIAAAABBfv///8eU3lzdGVtLldpbmRvd3MuRm9ybXMuU29ydE9yZGVyAQAAAAd2YWx1ZV9fAAgDAAAAAQAAAAkGAAAACQcAAAAJCAAAAAQGAAAAHFN5c3RlbS5Db2xsZWN0aW9ucy5BcnJheUxpc3QDAAAABl9pdGVtcwVfc2l6ZQhfdmVyc2lvbgUAAAgICQkAAAAFAAAABQAAAAEHAAAABgAAAAkKAAAABQAAAAUAAAABCAAAAAYAAAAJCwAAAAUAAAAFAAAAEAkAAAAIAAAACAEBCAEBCAEBCAEBCAEBDQMQCgAAAAgAAAAICAAAAAAICAEAAAAICAMAAAAICAQAAAAICAIAAAANAxALAAAACAAAAAgIzAAAAAgIRgAAAAgITgAAAAgIzAAAAAgISwAAAA0DCw==")]
        public string ObjectListViewTransactionsState {
            get {
                return ((string)(this["ObjectListViewTransactionsState"]));
            }
            set {
                this["ObjectListViewTransactionsState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Sales_Manager.RegistrySettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600000")]
        public int AutoRefreshInterval {
            get {
                return ((int)(this["AutoRefreshInterval"]));
            }
            set {
                this["AutoRefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Sales_Manager.RegistrySettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeToTray {
            get {
                return ((bool)(this["MinimizeToTray"]));
            }
            set {
                this["MinimizeToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Sales_Manager.RegistrySettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableUpdateNotification {
            get {
                return ((bool)(this["EnableUpdateNotification"]));
            }
            set {
                this["EnableUpdateNotification"] = value;
            }
        }
    }
}
